### ISSUE TITLE
README Update

### ISSUE THREAD

**Issue by ahmedu007** [actions-on-google/actionssdk-say-number-nodejs#10]
in the readme, the command `gactions update` is returning an error:
```
[ERROR] unknown command "update" for "gactions"
```

`gactions push` doesn't work the same way. I couldn't find another way to do it. Please help

**Comment by taycaldwell** [comment]
Hi @ahmedu007,

This sample refers to the legacy version of Actions SDK and the gactions CLI.

You can download legacy version of the gactions CLI [here](https://developers.google.com/assistant/conversational/df-asdk/actions-sdk/gactions-cli).

**Comment by ahmedu007** [comment]
Oh that's fantastic. Thanks for such a quick response @taycaldwell

**Comment by LeDuyNe** [comment]
> Hi @ahmedu007,
> 
> This sample refers to the legacy version of Actions SDK and the gactions CLI.
> 
> You can download legacy version of the gactions CLI [here](https://developers.google.com/assistant/conversational/df-asdk/actions-sdk/gactions-cli).

hey sir, Can you give me some versions lower than 3.2, currently I only see 3.2
