### ISSUE TITLE
Web Simulator

### ISSUE THREAD

**Issue by Gandhimathisr** [actions-on-google/actionssdk-say-number-nodejs#2]
Hi,

Am a newbee. I followed all the instructions for install and deploying 
As Gcloud deploy didn't work i used ngrok 

D:\GooleHome\sdk-dir\gactions preview --action_package action.json --invocation_name "hello action" -- preview_mins 1234
Pushing action 'hello action' for testing...
'hello action' is now available for you until 2017-02-10 12:16PM IST (29 minutes from now)
Try 'gactions simulate', then 'talk to hello action', or use the Web Simulator at https://g.co/actionswebsim

When I tried both gactiosn simulate or Web Simulator , all the below triggers/actions am getting ' actions is not available'
1. talk to hello action
2.hello action
3.At hello action

My question is does this sample app work with ngrok

**Comment by LeonNicholls** [comment]
Yes, the sample does work with ngrok. Did you update the action.json HTTP endpoint URL to use the ngrok URL?

**Comment by Gandhimathisr** [comment]
Hi 
Yes I did update the HTTP endpoint URL with the ngrok URL ( I used to get something like this https://8f94dad4.ngrok.io )

glcloud deploy gives error as "You do not have permission to access project [i-backbone-158206] (or it may not exist): Service 'cloudbuild.googleapis.com' is not enabled for consumer 'project:i-backbone-158206'"
Am not sure how to enable this API? Should I have to pay for gcloud account?

Cheers
Mathi
