### ISSUE TITLE
About engine field

### ISSUE THREAD

**Issue by zehrasubas** [actions-on-google/actionssdk-say-number-nodejs#7]
Even though I installed latest version of Node.js it gives me the error below when I deploy functions.

Error: package.json in functions directory has an engines field which is unsupported. The only valid choices are: {"node": "8"} and {"node": "6"}.

I had to remove the part below from package.json file to make it work:

  "engines": {
    "node": ">=6.11.1"
  }

**Comment by Canain** [comment]
Thanks for reporting the issue! The issue should be fixed now with aef507de98049e08e5ea91644e67a3d273088b64.

Let us know if you run into more issues.
