### ISSUE TITLE
README needs to be updated.

### ISSUE THREAD

**Issue by kyolee310** [actions-on-google/actionssdk-say-number-nodejs#9]
A step in the installation instructions on the README file is outdated.

In the step 3:

On the left navigation menu under BUILD, click on Actions. Click on Add Your First Action and choose your app's language(s).

When you click **ADD YOUR FIRST ACTION**, the console no longer displays the options to choose the language. Instead, it opens up a module that asks users to create action using Custom intent, Built-in intent, Templates, and Home automation.

**Comment by findzaatar** [comment]
Closing because the sample has been updated, thank you!
